### ISSUE TITLE
alias file not found even its set and `mutt -Q alias_file` provides that.

### ISSUE THREAD

**Issue by Awan** [Konfekt/mutt-alias.sh#5]
![image](https://user-images.githubusercontent.com/42554663/80001077-6674ff00-84d7-11ea-8b6b-2106376814d3.png)

**Comment by Konfekt** [comment]
Thank you for pointing this out.  Your `muttrc` has a non-standard path. The check for the existence of the `mutt` exectuable in `$PATH` was wrong, but is now fixed in 706ea2c58c27123a82f05de01ba96f95c7c54fdb .

**Comment by Awan** [comment]
On 22/04, Konfekt wrote:
>Thank you for pointing this out.  Your `muttrc` has a non-standard path. The check for the existence of the `mutt` exectuable in `$PATH` was wrong, but is now fixed in 706ea2c58c27123a82f05de01ba96f95c7c54fdb .
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/Konfekt/mutt-alias.sh/issues/5#issuecomment-617912054

I have fetched the  706ea2c58c27123a82f05de01ba96f95c7c54fdb but its still not working.


Abdullah

https://abdullah.today

C20F 2707 3025 2569 BAC5
534B 7820 6670 C19D 1580

**Comment by Awan** [comment]
The path to my muttrc is `$HOME/.config/mutt/muttrc`.

**Comment by Konfekt** [comment]
True, this was a vespiary of wrong code that you unhid. 031c6c39dc3191d94792e575880b6edb699c4578 should have fixed this.

**Comment by Awan** [comment]
On 22/04, Konfekt wrote:
>True, this was a vespiary of wrong code that you unhid. 031c6c39dc3191d94792e575880b6edb699c4578 should have fixed this.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/Konfekt/mutt-alias.sh/issues/5#issuecomment-617968938

Just updated the script after 031c6c39dc3191d94792e575880b6edb699c4578
but still same issue.


Abdullah

https://abdullah.today

C20F 2707 3025 2569 BAC5
534B 7820 6670 C19D 1580

**Comment by Awan** [comment]
![image](https://user-images.githubusercontent.com/42554663/80023095-7223ee00-84f6-11ea-928d-302793eac61a.png)

**Comment by Konfekt** [comment]
Are you sure that the alias file `hello` exists? Try without `-a`.

**Comment by Awan** [comment]
I'm using [stow](https://www.gnu.org/software/stow/) for my
[dotfiles](https://github.com/Awan/cfg) management. I can see you have
same approach but with a [shell
script](https://github.com/Konfekt/symlink-dotfiles.sh) so I don't think
that's a problem. Is that?

**Comment by Awan** [comment]
I'm using [stow](https://www.gnu.org/software/stow/) for my
[dotfiles](https://github.com/Awan/cfg) management. I can see you have
same approach but with a [shell script](https://github.com/Konfekt/symlink-dotfiles.sh) so I don't think that's a problem. Is that?

**Comment by Awan** [comment]
> Are you sure that the alias file `hello` exists? Try without `-a`.

yeah now its working without `-a` flag.

**Comment by Konfekt** [comment]
No. I never used this shell script yet as I am working on a single computer; [this](https://konfekt.github.io/blog/2018/11/10/simple-dotfiles-setup) is my approach but perhaps better is [aliasing git to dotfiles](https://blog.alionet.org/fr/2020-03-29_gerer_ses_dotfiles_avec_git). [yadm](https://github.com/TheLocehiliosan/yadm/blob/master/yadm) seems to be a fancy version of this.

**Comment by Konfekt** [comment]
My approach is similar to [this](https://drewdevault.com/2019/12/30/dotfiles.html), in being explicit about adding dotfiles by an inverted `.gitignore`, but symlinks all files starting with a dot.

**Comment by Awan** [comment]
Cool. I'm using [stow](https://www.gnu.org/software/stow). For encrypting some important files I have a strategy and I have written a [post](https://abdullah.today/encrypted-dotfiles/) on that.

**Comment by Konfekt** [comment]
Yes, I already read it. Interesting. Would be nice if you could compare it to `yadm`'s encryption or say using [Tomb](https://github.com/dyne/Tomb)
